#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : efitools
Version  : 1.9.2
Release  : 9
URL      : https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git/snapshot/efitools-1.9.2.tar.gz
Source0  : https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git/snapshot/efitools-1.9.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: efitools-bin = %{version}-%{release}
Requires: efitools-data = %{version}-%{release}
Requires: efitools-license = %{version}-%{release}
Requires: efitools-man = %{version}-%{release}
Requires: gnu-efi
BuildRequires : gnu-efi
BuildRequires : gnu-efi-dev
BuildRequires : gnu-efi-staticdev
BuildRequires : help2man
BuildRequires : openssl-dev
BuildRequires : perl
BuildRequires : perl-File-Slurp
BuildRequires : sbsigntools

%description
How to use these files
simply typing make will build you everything including sample certificates for
PK, KEK and db.

%package bin
Summary: bin components for the efitools package.
Group: Binaries
Requires: efitools-data = %{version}-%{release}
Requires: efitools-license = %{version}-%{release}

%description bin
bin components for the efitools package.


%package data
Summary: data components for the efitools package.
Group: Data

%description data
data components for the efitools package.


%package license
Summary: license components for the efitools package.
Group: Default

%description license
license components for the efitools package.


%package man
Summary: man components for the efitools package.
Group: Default

%description man
man components for the efitools package.


%prep
%setup -q -n efitools-1.9.2
cd %{_builddir}/efitools-1.9.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604709255
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make


%install
export SOURCE_DATE_EPOCH=1604709255
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/efitools
cp %{_builddir}/efitools-1.9.2/COPYING %{buildroot}/usr/share/package-licenses/efitools/32405cbbf3d377f39f8cfca3a013e565aa752c7d
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cert-to-efi-hash-list
/usr/bin/cert-to-efi-sig-list
/usr/bin/efi-readvar
/usr/bin/efi-updatevar
/usr/bin/efitool-mkusb
/usr/bin/flash-var
/usr/bin/hash-to-efi-sig-list
/usr/bin/sig-list-to-certs
/usr/bin/sign-efi-sig-list

%files data
%defattr(-,root,root,-)
/usr/share/efitools/COPYING
/usr/share/efitools/README
/usr/share/efitools/efi/HashTool.efi
/usr/share/efitools/efi/HelloWorld.efi
/usr/share/efitools/efi/KeyTool.efi
/usr/share/efitools/efi/Loader.efi
/usr/share/efitools/efi/LockDown.efi
/usr/share/efitools/efi/ReadVars.efi
/usr/share/efitools/efi/SetNull.efi
/usr/share/efitools/efi/ShimReplace.efi
/usr/share/efitools/efi/UpdateVars.efi

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/efitools/32405cbbf3d377f39f8cfca3a013e565aa752c7d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cert-to-efi-hash-list.1
/usr/share/man/man1/cert-to-efi-sig-list.1
/usr/share/man/man1/efi-readvar.1
/usr/share/man/man1/efi-updatevar.1
/usr/share/man/man1/hash-to-efi-sig-list.1
/usr/share/man/man1/sig-list-to-certs.1
/usr/share/man/man1/sign-efi-sig-list.1
