#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : efitools
Version  : 1.8.0
Release  : 1
URL      : https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git/snapshot/efitools-1.8.0.tar.gz
Source0  : https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git/snapshot/efitools-1.8.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0+LGPL-2.1
Requires: efitools-bin
Requires: efitools-data
Requires: efitools-doc
Requires: gnu-efi
BuildRequires : gnu-efi
BuildRequires : gnu-efi-dev
BuildRequires : help2man
BuildRequires : openssl-dev
BuildRequires : perl
BuildRequires : perl-File-Slurp
BuildRequires : sbsigntools

%description
How to use these files
simply typing make will build you everything including sample certificates for
PK, KEK and db.

%package bin
Summary: bin components for the efitools package.
Group: Binaries
Requires: efitools-data

%description bin
bin components for the efitools package.


%package data
Summary: data components for the efitools package.
Group: Data

%description data
data components for the efitools package.


%package doc
Summary: doc components for the efitools package.
Group: Documentation

%description doc
doc components for the efitools package.


%prep
%setup -q -n efitools-1.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518406199
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1518406199
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cert-to-efi-hash-list
/usr/bin/cert-to-efi-sig-list
/usr/bin/efi-readvar
/usr/bin/efi-updatevar
/usr/bin/efitool-mkusb
/usr/bin/flash-var
/usr/bin/hash-to-efi-sig-list
/usr/bin/sig-list-to-certs
/usr/bin/sign-efi-sig-list

%files data
%defattr(-,root,root,-)
/usr/share/efitools/COPYING
/usr/share/efitools/README
/usr/share/efitools/efi/HashTool.efi
/usr/share/efitools/efi/HelloWorld.efi
/usr/share/efitools/efi/KeyTool.efi
/usr/share/efitools/efi/Loader.efi
/usr/share/efitools/efi/LockDown.efi
/usr/share/efitools/efi/ReadVars.efi
/usr/share/efitools/efi/SetNull.efi
/usr/share/efitools/efi/ShimReplace.efi
/usr/share/efitools/efi/UpdateVars.efi

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
